name: "Release: Prod"

on:
  workflow_call:
    inputs:
      release_type:
        description: 'Type of release (stable, alpha, beta)'
        required: false
        type: string
        default: 'stable'
    secrets:
      GH_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release (stable, alpha, beta)'
        required: false
        type: choice
        default: 'stable'
        options:
          - 'stable'
          - 'alpha'
          - 'beta'

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    uses: aaronginder/workflow-factory/.github/workflows/semantic-release.yml@v1.1.1
    with:
      release_type: ${{ inputs.release_type }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
